waitFor(2000)
//   .then(() => console.log('Executing promise 1...'))
//   .then(waitFor)
//   .then(() => console.log('Executing promise 2...'))
//   .then(waitFor)
//   .then(() => console.log('Executing promise 3...'))
//   .then(waitFor)